apiVersion: v1
kind: Service
metadata:
  name: testnet 
  namespace: testnet
  labels:
    app: testnet
spec:
  ports:
%{ for name, port in ports }
  - name: ${name}
    port: ${port}
%{ endfor }
  clusterIP: None
  selector:
    app: testnet
